-- Таблица Book
CREATE TABLE IF NOT EXISTS Book (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author VARCHAR(255) NOT NULL,
    bookTitle VARCHAR(255) NOT NULL,
    isbn VARCHAR(255) UNIQUE NOT NULL,
    publicationYear INT NOT NULL,
    description TEXT,
    storageArrivalDate TIMESTAMP
);

-- Таблица BookCopies
CREATE TABLE IF NOT EXISTS BookCopies (
    copy_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id INT REFERENCES Book(id) ON DELETE CASCADE,
    copy_status VARCHAR(20) NOT NULL CHECK (copy_status
	IN ('AVAILABLE', 'RENTED')));
