-- Таблица Rental
CREATE TABLE IF NOT EXISTS Rental (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES Users(id) ON DELETE CASCADE,
    copy_id INT REFERENCES BookCopies(copy_id) ON DELETE CASCADE,
    start_date TIMESTAMP,
    due_date TIMESTAMP,
    return_date TIMESTAMP,
    rental_status VARCHAR(20) NOT NULL CHECK (rental_status
	IN ('RENTED', 'LATE', 'RETURNED'))
);
