-- Таблица Catalogs
CREATE TABLE IF NOT EXISTS Catalogs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    parent_id INT REFERENCES Catalogs(id) ON DELETE SET NULL
);

-- Таблица BookCatalogs
CREATE TABLE IF NOT EXISTS BookCatalogs (
    book_id INT REFERENCES Book(id) ON DELETE CASCADE,
    catalog_id INT REFERENCES Catalogs(id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, catalog_id)
);